language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - echo 'build successful, deploying...'

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_API_KEY 
  app: industrial-training-backend 
  on:
    branch: master